### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by k4r7u** [RichJack/Chromixium#2]
It would be great to have the option to set a proxy in the Control Panel instead of setting the environment variables in the terminal.
Thanks

**Comment by RichJack** [comment]
As yet there isn't a one-size fits all proxy GUI for Linux, but I'll see what I can do...

**Comment by k4r7u** [comment]
Thanks for the quick reply. 
Due to switching a lot between work behind a proxy and home, setting the environment variables isn't very practical and some kind of GUI would be awesome.

Thanks in advance.

**Comment by RichJack** [comment]
There is a way to do this actually, but it'll be a while before I can make it happen in Chromixium. However, if you want to try. First install Gnome Control Center:

sudo apt-get install gnome-control-center

You won't see it in the applications menu because it is a Gnome only app, but you can launch it. Hit the Run Command (Alt+F2) and then type:

gnome-control-center network

There is a Network Proxy GUI that you can use to set the proxy system-wide.
Pin it to the dock, so you don't misplace it!

Otherwise there are quite a few Chrome extensions for quickly turning a proxy on/off which will only work in the browser, but might be handy:
https://chrome.google.com/webstore/detail/proxy-switchysharp/dpplabbmogkhghncfbfdeeokoefdjegm?utm_source=chrome-ntp-icon

**Comment by k4r7u** [comment]
This workaround fixes the issue for me.
Nevertheless it would be awesome to have something like this in the control panel.

**Comment by RichJack** [comment]
If I can pluck it out from the gnome control centre then I might be able to include it...
