### ISSUE TITLE
keyboard setting 

### ISSUE THREAD

**Issue by cagatayldzz** [RichJack/Chromixium#7]
How do I make Turkish keyboard ?

**Comment by Feathur** [comment]
You should be able to set that during the initial install. If you've already installed right click the desktop and go into settings > keyboard.

**Comment by RichJack** [comment]
Depends on the version of Chromixium you are using, but the latest x64 RC5 has the keyboard setting in the Control Panel. Otherwise open a terminal and type:
`sudo dpkg-reconfigure -fgnome keyboard-configuration`

You may also want to set Turkish as a system-wide language using the Control Panel --> Language Support utility.

**Comment by cagatayldzz** [comment]
@Feathur  @RichJack , thank you
